### ISSUE TITLE
Add 3x2 SVD example to README.md

### ISSUE THREAD

**Issue by XeniaGabriela** [Quant-X-Security-Coding-GmbH/svd-challenge#8]
Insert at line 23:

![image](https://user-images.githubusercontent.com/13744209/128636989-5aec33a4-8b0d-4be1-93ab-21b011289a43.png)

**Comment by PeterNo-ai** [comment]
OK, mach ich---kein Problem.

**Comment by XeniaGabriela** [comment]
Implemented with commit https://github.com/Quant-X-Security-Coding-GmbH/svd-challenge/commit/48122c79bdd1b35aacaf1a1f31260f8a997f2d2d
